"""module2

Revision ID: 437acdb6b0f2
Revises: fad1d26171e2
Create Date: 2026-08-29 19:56:03.337163+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '437acdb6b0f2'
down_revision: Union[str, None] = 'fad1d26171e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable vector extension
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_problem_text', sa.String(), nullable=False),
    sa.Column('structured_outcome_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_structuring_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('budget_ceiling', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), server_default='INR', nullable=False),
    sa.Column('timeline_start', sa.Date(), nullable=True),
    sa.Column('timeline_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_eligibility_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('criteria_key', sa.String(), nullable=False),
    sa.Column('criteria_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_waivable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('waiver_reason_required', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_eligibility_criteria')
    op.drop_table('challenges')
    op.drop_table('sectors')
    # ### end Alembic commands ###
